# Cloudflare Workers configuration
name = "myminishelf-api"
main = "bookshelf-api.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard)
# [env.production.vars]
# OPENAI_API_KEY = "your-openai-api-key"

# KV namespace for production storage
# [[kv_namespaces]]
# binding = "SHELVES"
# id = "your-kv-namespace-id"